//Almateria's restoration pack
ACTION_IF MOD_IS_INSTALLED ~setup-arestorationp.tp2~ ~3~ BEGIN // Restored items
  PRINT @21
  SPRINT $item_source("boot08") ~viekang.cre~   // Boots of Phasing  |  Viekang SoA
  SPRINT $item_source("boot08") ~sarvie01.cre~  // Boots of Phasing  |  Viekang ToB
  SPRINT $item_source("boot10") ~habib.cre~     // Boots of Lightning speed  |  Habib
  SPRINT $item_source("boot10") ~habib2.cre~    // Boots of Lightning speed  |  Habib
  // OUTER_SPRINT ffbart_boot ~boot07~ // for custom.tph, Thunderburp's boots for Mazzy
END
