PRINT @25

COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
  PATCH_IF NOT (VARIABLE_IS_SET $source_item(~%SOURCE_FILE%~)) BEGIN
    LPF DELETE_CRE_ITEM
      STR_VAR
        item_to_delete = ~%all_items%~
    END
  END ELSE BEGIN
    LPF define_items
      STR_VAR
        exclude_source = ~%SOURCE_FILE%~
      RET
        all_items = items
    END
    LPF DELETE_CRE_ITEM
      STR_VAR
        item_to_delete = ~%all_items%~
    END
    SPRINT all_items ~%really_all_items%~
  END
BUT_ONLY
